{{- define "common.image" -}}
{{ $registry := .root.Values.global.imageRegistry | default .image.registry }}
{{- if $registry -}}
{{ $registry }}/{{ .image.repository }}:{{ .image.tag | default .root.Chart.Version }}
{{- else -}}
{{ .image.repository }}:{{ .image.tag | default .root.Chart.Version }}
{{- end -}}
{{- end -}}
