---
{{- if and (eq .Values.persistence.type "CloudNativePG") }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.persistence.cloudNativePG.name }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.persistence.cloudNativePG.replicas }}
  storage:
    size: {{ .Values.persistence.cloudNativePG.size }}
  bootstrap:
    initdb:
      database: {{ .Values.persistence.cloudNativePG.database }}
      owner: {{ .Values.persistence.cloudNativePG.owner }}
  monitoring:
    enablePodMonitor: true
{{- end }}
