---
apiVersion: batch/v1
kind: Job
metadata:
  name: po-wallet-migrate-job-{{ .Chart.AppVersion }}
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: po-wallet-migrate-job-{{ .Chart.AppVersion }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        args: ["--migrate"]
        env:
        {{ if .Values.persistance.cloudNativePG.enabled }}
          - name: DB_HOST
            value: {{ .Values.persistance.cloudNativePG.name }}-rw
          - name: DB_PORT
            value: "5432"
          - name: DB_DATABASE
            value: {{ .Values.persistance.cloudNativePG.size }}
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.persistance.cloudNativePG.name }}-superuser
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.persistance.cloudNativePG.name }}-superuser
                key: password
          - name: ConnectionStrings__Database
            value: Host=$(DB_HOST); Port=$(DB_PORT); Database=$(DB_DATABASE); Username=$(DB_USERNAME); Password=$(DB_PASSWORD);
        {{ end }}
