name: Verify code on PR

on:
  pull_request:
    branches:
      - main

jobs:
  verify-code:
    name: Verifies code formatting, builds, and runs unit tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK from global.json
        uses: actions/setup-dotnet@v4

      - name: Print info
        run: make info

      - name: Build code
        run: make build

      - name: Run tests
        run: make test

      - name: Verify formatting
        run: make lint

      - name: Verify no changes
        run: |
          git diff --exit-code
          git diff --cached --exit-code

