name: Verifies that the chart can be installed, migration runs and the wallet beecomes ready.

on:
  pull_request:
    branches:
      - main

jobs:
  verify-chart-with-latest-container:
    name: Verify chart with local built container
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Start kind cluster
        run: make verify-container-chart

  verify-chart-with-current-app-version-container:
    name: Verify chart with current appVersion container
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Start kind cluster
        run: make verify-chart
