name: Verifies that the chart can be installed, migration runs and the wallet beecomes ready.

on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      image_tag: local-test
    steps:
      - uses: actions/checkout@v3

      - name: Start kind cluster
        run: kind create cluster

      - name: Install Cloudnative-pg operator
        run: helm install cnpg-operator cloudnative-pg --repo https://cloudnative-pg.io/charts --version 0.18.0 --namespace cnpg --create-namespace

      - name: Build image
        run: docker build -f src/ProjectOrigin.WalletSystem.Server/Dockerfile -t ghcr.io/project-origin/wallet-server:${{ env.image_tag }} src/

      - name: Load image into kind cluster
        run: kind load docker-image ghcr.io/project-origin/wallet-server:${{ env.image_tag }}

      - name: Install chart
        run: helm install wallet charts/project-origin-wallet --set image.tag=${{ env.image_tag }}

      - name: Wait for chart to be ready
        run: kubectl wait --for=condition=ready pod -l app=po-wallet --timeout=300s
