name: Verify Chart works on PR

on:
  pull_request:
    branches:
      - main

jobs:
  verify-chart:
    name: Verify chart with local built container
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Start kind cluster
        run: make verify-chart
