name: Verify container builds on PR

on:
  pull_request:
    branches:
      - main

jobs:
  verify-container-build:
    uses: project-origin/.github/.github/workflows/reusable-build-push-container-ghcr.yaml@main
    with:
      imagename: ghcr.io/project-origin/wallet-server
      version: test
      context: ./src
      dockerfile: ./src/ProjectOrigin.WalletSystem.Server/Dockerfile
      push: false
